import { InferenceClient } from "@huggingface/inference";
import { generateViralScriptPrompt, nicheThemes } from "./prompts";

export class AIService {

    private hf: InferenceClient;

    constructor() {
        this.hf = new InferenceClient(process.env.HF_TOKEN);
    }

    async generateViralScript(
        prompt: string,
        niche: string,
        purpose = "",
        description = "",
        brandName = "",
        callCount = 0
    ) {

        const systemPrompt = generateViralScriptPrompt(
            prompt,
            niche,
            purpose,
            description,
            brandName,
            callCount
        );

        const response = await this.hf.chatCompletion({
            model: "meta-llama/Meta-Llama-3-8B-Instruct",
            messages: [{ role: "user", content: systemPrompt }],
            max_tokens: 500,
            temperature: 0.7
        });

        const text = response.choices[0].message.content;

        if (!text) {
            throw new Error("No content generated by AI");
        }

        return JSON.parse(text);
    }

    async generateBackgroundImage(niche: string) {

        const theme = nicheThemes[niche.toLowerCase()] ?? {
            colors: "dark gradient background",
            icons: "minimal geometric shapes",
            mood: "clean social media graphic",
            typography: "bold sans serif"
        };

        const prompt = `
minimal social media background
${theme.colors}
${theme.icons}
${theme.mood}

NO TEXT
NO WORDS
abstract graphic background
`;

        const image = await this.hf.textToImage({
            model: "stabilityai/stable-diffusion-xl-base-1.0",
            inputs: prompt
        });

        const buffer = Buffer.from(await (image as any).arrayBuffer());

        return `data:image/png;base64,${buffer.toString("base64")}`;
    }

}

export const aiService = new AIService();